### ISSUE TITLE
Hard coding

### ISSUE THREAD

**Issue by abdulatifkhan** [rasuloff789/howmany-fizzbuzz#1]
Kod haddan tashqari yaqin, bu o'qishni qiyinlashtiradi. Bu darajada hasislik yaramaydi!)))

![image](https://user-images.githubusercontent.com/68887519/98638062-3134df00-234b-11eb-8537-7c3c001c6baa.png)

**Comment by ozbeg** [comment]
**Tushunolmadizmi deyman 👍**

**Comment by ozbeg** [comment]
_Tekshirish_

**Comment by abdulatifkhan** [comment]
Tushundim, foydalanuvchi lekin o'zi tushunishi uchun ham bir tartib bilan, ajratib yozilsa, maqsadga muvofiq bo'lardi)

**Comment by ozbeg** [comment]
fix hard coding
